### NumPy

https://numpy.org/

In [1]:
import numpy as np       #Importando o pacote numpy e nomeando-o como 'np'.

In [2]:
np.__version__

'1.26.4'

In [1]:
!pip install numpy==1.22.2          

## Criando arrays NumPy

Um array NumPy é uma estrutura de dados multidimensional usada em computação científica e análise de dados. O NumPy fornece um objeto de matriz N-dimensional (ou ndarray), que é uma grade homogênea de elementos, geralmente números, que podem ser indexados por um conjunto de inteiros.

Os arrays NumPy são mais eficientes do que as listas Python para armazenar e manipular grandes quantidades de dados, pois são implementados em linguagem C e fornecem várias otimizações de desempenho. Além disso, o NumPy permite a fácil leitura e escrita de arquivos de dados, integração com outras bibliotecas Python e suporte a operações em paralelo usando várias CPUs ou GPUs.

In [4]:
arr1 = np.array([2,4,6,8,10,12,14,16,18,20])     #Array criado a partir de uma lista Python

In [5]:
type(arr1)

numpy.ndarray

In [8]:
arr1.shape               #Verificando o formato do array. Neste caso, temos apenas uma dimensão com 10 elementos.

(10,)

In [9]:
print(arr1)

[ 2  4  6  8 10 12 14 16 18 20]


In [10]:
arr1[3]    #Imprimindo um elemento específico no array.

8

In [12]:
arr1[1:4]   #Imprimindo um range do array.

array([4, 6, 8])

In [13]:
arr1[1:4+1]

array([ 4,  6,  8, 10])

In [19]:
ind = [0,1,2,3,4,5,6,7,8,9]      #Criando uma lista de índices.

In [20]:
arr1[ind]      #Imprimindo os elementos dos indices

array([ 2,  4,  6,  8, 10, 12, 14, 16, 18, 20])

In [6]:
mask = (arr1 % 3 == 0)     #Cria uma máscara booleana (TRUE or FALSE) para os elementos do array que são divisíveis por 3

In [7]:
mask

array([False, False,  True, False, False,  True, False, False,  True,
       False])

In [8]:
arr1[mask]     #Retorna os elementos do array cuja máscara retorna TRUE.

array([ 6, 12, 18])

In [9]:
arr1[9] = 100      #Alterando um elemento (indexado) do array.

In [10]:
arr1

array([  2,   4,   6,   8,  10,  12,  14,  16,  18, 100])

In [11]:
try: 
    arr1[0] = 'texto'
except:
    print('Operação inválida.')        #Não é possível incluir elementos de outro tipo no array.

Operação inválida.


## Funções NumPy

In [13]:
arr2 = np.arange(0,50,5)   #O método arange cria um array contendo uma progressão aritmética a partir de intervalos
                            # - (start, stop, step).

In [14]:
arr2

array([ 0,  5, 10, 15, 20, 25, 30, 35, 40, 45])

In [15]:
arr0 = np.zeros(10)     #Cria um array com zeros. 10 é o tamanho do array.

In [17]:
print(arr0)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


In [27]:
print(np.linspace(0,20,11))     

[ 0.  2.  4.  6.  8. 10. 12. 14. 16. 18. 20.]


A função linspace() do NumPy é usada para criar uma sequência de de números igualmente espaçados dentro de um intervalo especificado. Esta função é utilizada para gerar arrays de números para diversos fins, como gráficos, simulações, etc.

No caso acima, queremos 11 valores igualmente espaçados entre 0 e 20.

In [40]:
print(np.logspace(1,4,4))

[   10.   100.  1000. 10000.]


A função logspace() do NumPy é usada para criar uma sequência de números igualmente espaçados em escala logarítimica dentro de um intervalo especificado.

No caso acima, querermos 4 valores igualmente espaçados em escala logarítmica entre log(10) = 1 e log(10 000) = 4.

## Matrizes

In [41]:
mat1 = np.array([[1,2,3] , [4,5,6]])     #Criando uma matriz de duas linhas e três colunas. 

In [42]:
print(mat1)

[[1 2 3]
 [4 5 6]]


In [44]:
mat1.shape         #Verificando o formato do array. Neste caso temos uma matriz (bidimensional) 2x3.

(2, 3)

In [45]:
lista = [[1,2,3,4] , [5,6,7,8] , [9,10,11,12]]

In [46]:
mat2 = np.matrix(lista)       #O método matrix() cria uma matriz a partir de uma lista. Usar este método é mais
                              # interessante para operações matemáticas.

In [47]:
mat2

matrix([[ 1,  2,  3,  4],
        [ 5,  6,  7,  8],
        [ 9, 10, 11, 12]])

In [48]:
print(mat2)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


In [49]:
mat2.shape

(3, 4)

In [50]:
mat2.size         # Este atributo verifica a quantidade de elementos na matriz.

12

In [51]:
mat2[0,3]     #Indexação de um elemento na matriz.

4

In [57]:
print(mat2[1,])  #Indexação de uma linha da matriz.

[[5 6 7 8]]


In [58]:
print(mat2[:,2])      #Indexação de uma coluna da matriz.     

[[ 3]
 [ 7]
 [11]]


In [66]:
print(mat2[:,2].flatten())       #transformando a coluna em linha.

[[ 3  7 11]]


In [60]:
mat2.itemsize            #O atributo itemsize retorna o valor, em bytes, ocupado por cada elemento na matriz.

4

In [62]:
mat2.nbytes             #O atributo nbytes retorna o valor, em bytes, ocupado por toda a matriz 12 elementos x 4 = 48

48

In [63]:
mat2.ndim        # O atributo ndim retorna o número de dimensões da matriz.

2

### Matrizes multidimensionais

In [3]:
arr_3d = np.array([ [[1,2,3,4]     , [5,6,7,8]     , [9,10,11,12]],
                   [[13,14,15,16] , [17,18,19,20] , [21,22,23,24]]   ])

In [4]:
print(arr_3d)

[[[ 1  2  3  4]
  [ 5  6  7  8]
  [ 9 10 11 12]]

 [[13 14 15 16]
  [17 18 19 20]
  [21 22 23 24]]]


In [5]:
arr_3d.ndim

3

In [6]:
arr_3d.shape

(2, 3, 4)

In [7]:
arr_3d[0,1,2]   #Indexando um elemento da matriz

7

In [8]:
arr_3d[0,2]    #Indexando um elemento unidimensional

array([ 9, 10, 11, 12])

## Manipulando arquivos com NumPy

In [9]:
import os                              #Chamando o sistema operacional

filename = os.path.join('arq.csv')      #Buscando caminho do arquivo

In [10]:
!more arq.csv

ID,Nome,Idade,Cidade,Profissão,Salário (R$)
1,João Silva,34,São Paulo,Engenheiro,8500.00
2,Maria Lima,28,Rio de Janeiro,Médica,12300.00
3,Pedro Rocha,45,Belo Horizonte,Professor,6700.00
4,Ana Souza,31,Salvador,Advogada,9100.00
5,Lucas Alves,22,Curitiba,Designer,5400.00
6,Carla Dias,29,Fortaleza,Jornalista,7200.00
7,Bruno Melo,38,Recife,Administrador,10500.00
8,Laura Nunes,26,Porto Alegre,Arquiteta,11000.00
9,Felipe Reis,40,Manaus,Médico,13200.00
10,Paula Cruz,35,Goiânia,Engenheira,9800.00
11,Gustavo Luz,42,Campinas,Gerente,14500.00
12,Fernanda Lu,27,Brasília,Psicóloga,8700.00
13,André Costa,33,Natal,Contador,7900.00
14,Mariana Tez,24,Florianópolis,Cientista,9300.00
15,Rafael More,39,São Luís,Desenvolvedor,10700.00
16,Beatriz San,30,Maceió,Farmacêutica,8600.00
17,Rodrigo Fi,36,Vitória,Economista,12100.00
18,Camila Brit,25,Teresina,Enfermeira,6900.00
19,Tiago Amar,41,Belém,Professor,7500.00
20,Priscila Vi,29,João Pessoa,Publicitária,9400.00


In [18]:
arr3 = np.loadtxt(filename, delimiter = ',', usecols = (0,2,5), skiprows = 1)  #Colocando o conteudo do arquivo numa array

In [19]:
print(arr3)

[[1.00e+00 3.40e+01 8.50e+03]
 [2.00e+00 2.80e+01 1.23e+04]
 [3.00e+00 4.50e+01 6.70e+03]
 [4.00e+00 3.10e+01 9.10e+03]
 [5.00e+00 2.20e+01 5.40e+03]
 [6.00e+00 2.90e+01 7.20e+03]
 [7.00e+00 3.80e+01 1.05e+04]
 [8.00e+00 2.60e+01 1.10e+04]
 [9.00e+00 4.00e+01 1.32e+04]
 [1.00e+01 3.50e+01 9.80e+03]
 [1.10e+01 4.20e+01 1.45e+04]
 [1.20e+01 2.70e+01 8.70e+03]
 [1.30e+01 3.30e+01 7.90e+03]
 [1.40e+01 2.40e+01 9.30e+03]
 [1.50e+01 3.90e+01 1.07e+04]
 [1.60e+01 3.00e+01 8.60e+03]
 [1.70e+01 3.60e+01 1.21e+04]
 [1.80e+01 2.50e+01 6.90e+03]
 [1.90e+01 4.10e+01 7.50e+03]
 [2.00e+01 2.90e+01 9.40e+03]]


In [22]:
arr3 = np.array(list(map(lambda x: list(map(int, x)), arr3)))        #conversão de not. cientifica para inteiro

In [23]:
print(arr3)

[[    1    34  8500]
 [    2    28 12300]
 [    3    45  6700]
 [    4    31  9100]
 [    5    22  5400]
 [    6    29  7200]
 [    7    38 10500]
 [    8    26 11000]
 [    9    40 13200]
 [   10    35  9800]
 [   11    42 14500]
 [   12    27  8700]
 [   13    33  7900]
 [   14    24  9300]
 [   15    39 10700]
 [   16    30  8600]
 [   17    36 12100]
 [   18    25  6900]
 [   19    41  7500]
 [   20    29  9400]]


In [24]:
var1,var2 = np.loadtxt(filename, delimiter = ',', usecols = (0,5), skiprows = 1, unpack = True)  #atribuido às duas variáveis
                                                                                                 # de arrays as colunas indicadas 
                                                                                                 # do arquivo.

In [25]:
var1          # verificando var1 e a coluna 0

array([ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10., 11., 12., 13.,
       14., 15., 16., 17., 18., 19., 20.])

In [26]:
var2        # verificando var2 e a coluna 5

array([ 8500., 12300.,  6700.,  9100.,  5400.,  7200., 10500., 11000.,
       13200.,  9800., 14500.,  8700.,  7900.,  9300., 10700.,  8600.,
       12100.,  6900.,  7500.,  9400.])

## Operações Matemáticas com Arrays

In [27]:
arr4 = np.arange(1,10)          #Criando um array com o método arange

In [28]:
print(arr4)

[1 2 3 4 5 6 7 8 9]


In [29]:
np.sum(arr4)         #Soma de todos os elementos do array

45

In [30]:
np.prod(arr4)      #produto de todos os elementos do array

362880

In [31]:
np.cumsum(arr4)    #Soma acumulada

array([ 1,  3,  6, 10, 15, 21, 28, 36, 45])

In [32]:
np.cumprod(arr4)     #Produto acumulado

array([     1,      2,      6,     24,    120,    720,   5040,  40320,
       362880])

In [33]:
arr5a = np.array([1,2,3])
arr5b = np.array([4,5,6])

In [34]:
arr5 = np.add(arr5a,arr5b)          #Adição elemento a elemento

In [35]:
print(arr5)

[5 7 9]


In [36]:
arr6a = [[4,6],[8,2],[5,3],[1,1]]
arr6b = [[2,2,2],[10,10,10]]

In [37]:
arr6 = np.dot(arr6a,arr6b)        #produto de matrizes

In [38]:
print(arr6)

[[68 68 68]
 [36 36 36]
 [40 40 40]
 [12 12 12]]


In [39]:
arr6c = np.dot(arr6b,arr6a)      #A ordem do produto importa, ver mensagem de erro abaixo.

ValueError: shapes (2,3) and (4,2) not aligned: 3 (dim 1) != 4 (dim 0)

## Slicing (fatiamento) de arrays

In [44]:
arr7 = np.diag([1,1,1])      #Criando uma matriz identidade

In [45]:
print(arr7)

[[1 0 0]
 [0 1 0]
 [0 0 1]]


In [46]:
arr8 = np.diag([3.14,2.71,1.61,1.41])      #Criando uma matriz diagonal com os elementos indicados

In [47]:
print(arr8)

[[3.14 0.   0.   0.  ]
 [0.   2.71 0.   0.  ]
 [0.   0.   1.61 0.  ]
 [0.   0.   0.   1.41]]


In [48]:
arr8[0,0]

3.14

In [49]:
arr8[2,2]

1.61

In [50]:
arr8[1]    #Indexando uma linha do array

array([0.  , 2.71, 0.  , 0.  ])

In [51]:
arr8[:,0]    #Indexando uma coluna do array

array([3.14, 0.  , 0.  , 0.  ])

In [52]:
arr9 = np.arange(20)

In [53]:
print(arr9)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19]


In [54]:
arr9[0:15:4]      #start:stop:step#

array([ 0,  4,  8, 12])

In [57]:
a = np.array([1,2,3,4])
b = np.array([4,2,2,4])

In [58]:
a == b     #Comparação item a item

array([False,  True, False,  True])

In [59]:
np.array_equal(a,b)   #Comparação global

False

In [60]:
print(arr8)

[[3.14 0.   0.   0.  ]
 [0.   2.71 0.   0.  ]
 [0.   0.   1.61 0.  ]
 [0.   0.   0.   1.41]]


In [61]:
arr8.min()      #Retorna o elemento de menor valor

0.0

In [62]:
arr8.max()       #Retorna o elemento de maior valor

3.14

In [64]:
arr10 = np.array([[1,2,3,4],[5,6,7,8]])

In [65]:
print(arr10)

[[1 2 3 4]
 [5 6 7 8]]


In [67]:
arr10 = arr10.flatten()    #'Achatando' os elementos para uma dimensão.

In [68]:
print(arr10)

[1 2 3 4 5 6 7 8]


In [69]:
arr11 = np.array([1,2,3])

In [70]:
arr12 = np.repeat(arr11,3)    #Repetindo os elementos, um por um, três vezes.

In [71]:
print(arr12)

[1 1 1 2 2 2 3 3 3]


In [72]:
arr13 = np.tile(arr11,3)      #Repetindo a sequência de elementos três vezes.

In [73]:
print(arr13)

[1 2 3 1 2 3 1 2 3]


In [74]:
arr14 = np.copy(arr11)       #copiando o array.

In [75]:
print(arr14)

[1 2 3]
